// <auto-generated />
using System;
using CustomTestCreator.TestHistories.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CustomTestCreator.TestHistories.Infrastructure.Migrations
{
    [DbContext(typeof(TestHistoryDbContext))]
    [Migration("20250131172951_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CustomTestCreator.TestHistories.Domain.TestHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CountOfAllAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("count_of_all_answers");

                    b.Property<int>("CountOfRightAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("count_of_right_answers");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime>("PassageTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("passage_time");

                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_id");

                    b.HasKey("Id")
                        .HasName("pk_test_histories");

                    b.ToTable("TestHistories", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
